<?php

namespace Striide\TinyurlBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends EntityRepository
{
  /**
   *
   * @return Striide\TinyurlBundle\Entity\Url
   */
  public function findLatest($limit = 50)
  {
    $query = $this->getEntityManager()->createQuery('
					SELECT u
					FROM Striide\TinyurlBundle\Entity\Url u
          ORDER BY u.created_at DESC
				');
    $query->setMaxResults($limit);
    try
    {
      $urls = $query->getResult();
      return $urls;
    }
    catch(\Doctrine\ORM\NoResultException $e)
    {
      return null;
    }
  }
}
